// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: DSL_FFT_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Scroll_bar = NULL;
lv_obj_t * ui_Account = NULL;
lv_obj_t * ui_Code = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_FobBob = NULL;
lv_obj_t * ui_Name = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 250);
    lv_obj_set_height(ui_Panel1, 250);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scroll_bar = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_Scroll_bar, 250);
    lv_obj_set_height(ui_Scroll_bar, 250);
    lv_obj_set_align(ui_Scroll_bar, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Scroll_bar, 50);
    lv_arc_set_bg_angles(ui_Scroll_bar, 270, 269);

    lv_obj_set_style_pad_left(ui_Scroll_bar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Scroll_bar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Scroll_bar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Scroll_bar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Account = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Account, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Account, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Account, 0);
    lv_obj_set_y(ui_Account, -35);
    lv_obj_set_align(ui_Account, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Account, "Account");
    lv_obj_set_style_text_font(ui_Account, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Code = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Code, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Code, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Code, 0);
    lv_obj_set_y(ui_Code, 5);
    lv_obj_set_align(ui_Code, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Code, "000000");
    lv_obj_set_style_text_color(ui_Code, lv_color_hex(0x007EF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Code, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Code, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, 60);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "YYYY-MM-DD HH:mm:ss");
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FobBob = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_FobBob, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FobBob, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FobBob, 0);
    lv_obj_set_y(ui_FobBob, 90);
    lv_obj_set_align(ui_FobBob, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FobBob, "FobBob");

    ui_Name = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name, 0);
    lv_obj_set_y(ui_Name, -90);
    lv_obj_set_align(ui_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name, "Gavin's Bob");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Scroll_bar = NULL;
    ui_Account = NULL;
    ui_Code = NULL;
    ui_Time = NULL;
    ui_FobBob = NULL;
    ui_Name = NULL;

}
